### ISSUE TITLE
Node stopped syncing - [Parachain] panicked at 'Storage root must match that calculated

### ISSUE THREAD

**Issue by stakeworks** [t3rn/t3rn#1199]
```
2023-07-20 21:10:21 [Parachain] panicked at 'Storage root must match that calculated.', /home/sysi-epyc/.cargo/git/checkouts/substrate-7e08433d4c370a21/5bfdbab/frame/execu      tive/src/lib.rs:479:9
2023-07-20 21:10:21 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreac      hable` instruction executed
WASM backtrace:
    0: 0x12b3c7 - <unknown>!rust_begin_unwind
    1: 0x6585e - <unknown>!core::panicking::panic_fmt::hc5ea0a1cbc69f084
    2: 0x1fa465 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hc7018f34ff0459af
    3: 0x562390 - <unknown>!Core_execute_block

2023-07-20 21:10:21 [Parachain] 💔 Error importing block 0xd438c7ca3c2808476531f78f5b8aa3fc845d149f94d1d758403c3fcf67d69b8b: consensus error: Import failed: Error at calli      ng runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
    0: 0x12b3c7 - <unknown>!rust_begin_unwind
    1: 0x6585e - <unknown>!core::panicking::panic_fmt::hc5ea0a1cbc69f084
    2: 0x1fa465 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hc7018f34ff0459af
    3: 0x562390 - <unknown>!Core_execute_block
```

Ubuntu: 22.04
Binary: t0rn-collator 1.42.1-rc.0-38a85b6f083

After restart node synced again

ExecStart=t0rn-collator \
        --collator \
        --chain=/t0rn.raw.json \
        --base-path /basepath/ \
        --name 'StakeWorks | T0RN | CMN05' \
        --bootnodes /dns/bootnode.t0rn.io/tcp/33333/p2p/12D3KooWEepV69XCJB4Zi193cZcm5W22ZR62DEP84iLFTUKVPtwp \
        --execution wasm \
        --pruning=archive \
        --prometheus-port 19645 \
        --prometheus-external \
        --port 30333 \
        --ws-port 9933 \
        --rpc-port 9944 \
        --rpc-methods=unsafe \
        --no-hardware-benchmarks \
        -- \
        --base-path /basepath/ \
        --chain /rococo.raw.json \
        --bootnodes /ip4/34.90.151.124/tcp/30333/p2p/12D3KooWF7BUbG5ErMZ47ZdarRwtpZamgcZqxwpnFzkhjc1spHnP \
        --execution wasm \
        --no-hardware-benchmarks \
        --pruning 1000 \

**Comment by robsonfs** [comment]
I think a restart would sort this out. For more information, take a look at [this thread](https://github.com/paritytech/polkadot/issues/413).

**Comment by stakeworks** [comment]
Yes, restart will fix this, but it shouldn't happen.

**Comment by 3h4x** [comment]
@stakeworks Thanks for the issue. We will investigate it in one of upcoming sprints!

**Comment by stakeworks** [comment]
@3h4x Node stops syncing regulary, looks like more people have this issue if I look at the telemetry. Since yesterday I restart the node every 2 hours with a cronjob. The node hasn't stopped syncing since.

**Comment by 3h4x** [comment]
> @3h4x Node stops syncing regulary, looks like more people have this issue if I look at the telemetry. Since yesterday I restart the node every 2 hours with a cronjob. The node hasn't stopped syncing since.

Are you running collator with `-state-cache-size 0` flag?

**Comment by stakeworks** [comment]
Yes, I've changed it yesterday. Didn't think of it at first because I thought state-cache-size was deprecated.
I will remove the cronjob and see if keeps syncing.

**Comment by stakeworks** [comment]
Node is still syncing after 14 hours , but block production is slow, compared to other chains. 

![image](https://github.com/t3rn/t3rn/assets/19406838/2b48dafd-38d6-4d63-b87d-a9e457d4bf0a)

**Comment by 3h4x** [comment]
> Node is still syncing after 14 hours , but block production is slow, compared to other chains.
> 
> ![image](https://user-images.githubusercontent.com/19406838/256480645-2b48dafd-38d6-4d63-b87d-a9e457d4bf0a.png)

It's difficult to me to say anything about the monitoring because I'm missing what those values actually are.
We are aware of delayed block production and within next substrate update it should go back to normal. 
Please remember that it's our dev testnet and we allow there some hickups.

**Comment by stakeworks** [comment]
I know it's a testnet, it is for information only

These are the headers 
![image](https://github.com/t3rn/t3rn/assets/19406838/2e636191-7be0-4820-b193-9a615daa7390)
![image](https://github.com/t3rn/t3rn/assets/19406838/59257bb5-537a-406a-b49b-8efd970b6c3f)

**Comment by 3h4x** [comment]
@stakeworks Good. We are on the same page then. 
Aaah it's how many blocks we produce per minute. Yes, elevated. The issue `Storage root must match that calculated ` should be already fixed with recent runtime upgrades.

https://github.com/t3rn/t3rn/pull/1222
