### ISSUE TITLE
Event not produced after sideEffects are submitted using the `onExtrinsicTrigger`

### ISSUE THREAD

**Issue by ahkohd** [t3rn/t3rn#242]
## Expected behavior
When you submit a side effect using `onExtrinsicTrigger`, it's expected to emit events or at least give you some staus about the submitted side effect.

### Actual behavior
No event is emitted and so the flags such as `isCompleted`,  `isError`,  `isInBlock`, `isWarning`, `isFinalized` are in their default values.

### Steps to reproduce
- Make sure you're running the stand-alone (ws://localhost:9944) from branch `update_v0.9.17` 
- Visit https://t3rn-alice.vercel.app
- Click on Execution
- Connect your Polkadot wallet or MetaMask (this does not affect this procedure on this staging environment, it's only used on prod to sign transactions)
- Click on the circular + button
- Add a transfer side effect, fill the form
- Open your console before you submit
- Submit the side-effects 
- Check your console for `submission result`.

This object is supposed to be emitted more than once as each object contains the recent status of the submitted side effects.

**Comment by MaciejBaj** [comment]
Solved by #297
