### ISSUE TITLE
Circuit skips confirmation for multiple side effects

### ISSUE THREAD

**Issue by beqaabu** [t3rn/t3rn#261]
## Expected behavior
Pallet circuit should handle submitting, validating, and confirming multiple side effects when calling `Circuit::on_extrinsic_trigger` with the `side_effects` argument containing a vector of several side effects.
### Actual behavior
In reality, circuit only confirms the first side effect in the vector, changes the status of the whole xtx to `Finished` and skips the remaining side effects without confirming them
### Steps to reproduce
The steps to reproduce the issue can be seen in `pallets/circuit/tests.rs` under the test `circuit_handles_transfer_and_swap` [here.](https://github.com/t3rn/t3rn/blob/383d758f9926d873ebab9d2f098927a654187918/pallets/circuit/src/tests.rs#L1071) The test is ignored for now to make the ci pass

**Comment by MaciejBaj** [comment]
Fixed by #279
