### ISSUE TITLE
on_extrinsic_trigger fails when setting a fee other then 0

### ISSUE THREAD

**Issue by petscheit** [t3rn/t3rn#262]
## Expected behavior
Setting a fee should be possible. In case there is a balance issue, an error should be thrown

### Actual behavior
The circuit fails silently when setting a fee other then 0. No error is propagated to polkadot-js, and the `circuit.NewSideEffectsAvailable` is not emitted. The transaction arrives at the circuit however, the transaction fee is deducted from the sender. 

### Steps to reproduce
I have created a separate repo showcasing this. Can be found here: https://github.com/petscheit/register_gateway

The fee can be set in `submit.ts`. Keep in mind that duplicate side_effects are currently not supported, so the easiest way for testing is to generate the target randomly for each run (uncomment below in index.ts). This will register a new gateway on each exec

**Comment by beqaabu** [comment]
I'm pretty sure the issue here is that Alice's balance is 0 and a fee greater than 0 can not be covered with it. `ChargingTransferFailed` error works fine for such cases in rust, not sure why is it not showing up in ts tests. 

See the code example below:
```
#[test]
fn on_extrinsic_trigger_works_with_empty_side_effects() {
    let origin = Origin::signed(ALICE); // Only sudo access to register new gateways for now

    let mut ext = TestExternalities::new_empty();
    let side_effects = vec![];
    let fee = 2;
    let sequential = true;

    ext.execute_with(|| {
        let _ = Balances::deposit_creating(&ALICE, 1); <----- test fails if balance is less than the fee

        assert_ok!(Circuit::on_extrinsic_trigger(
            origin,
            side_effects,
            fee,
            sequential,
        ));
    });
}
```
Running this test results in:
```
Expected Ok(_). Got Err(
    DispatchErrorWithPostInfo {
        post_info: PostDispatchInfo {
            actual_weight: None,
            pays_fee: Pays::Yes,
        },
        error: Module(
            ModuleError {
                index: 16,
                error: 1,
                message: Some(
                    "ChargingTransferFailed",
                ),
            },
        ),
    },
)
```
This test can be found [here](https://github.com/t3rn/t3rn/blob/9b777aeb4e9ba171add88d85186746dc473822b2/pallets/circuit/src/tests.rs#L44)
