### ISSUE TITLE
Add our custom RPC calls to the runtime

### ISSUE THREAD

**Issue by beqaabu** [t3rn/t3rn#287]
## Description

We have rpc methods for most of the pallets, but only wasm-contracts rpc is present in the runtime. It would be good to have access to other rpcs as well.

### Acceptance Criteria

Rpc runtime apis are added to the runtimes (standalone + para) under `impl_runtime_apis!` macro for pallets:
- [ ] Xdns
- [ ] Contracts registry
- [ ] Portal

**Comment by Doordashcon** [comment]
Hello @beqaabu I would like to take on this issue

I also see the RPC methods for Xdns has already been added to runtime

**Comment by allanperlee** [comment]
Hi @beqaabu ! I am interested in your organization, can I research and develop this issue?
