### ISSUE TITLE
Receive and process execution requests from API

### ISSUE THREAD

**Issue by t3rn** [t3rn/t3rn#29]
### Description

Receive execution requests from API and process them according to specified IO schedule.

### Acceptance Criteria

- [x] Create a new runtime module responsible for processing Circuit requests (a new Pallet). It will become the main Circuit engine and execution orchestrator. 
- [x] New Engine Pallet implements the `composable_exec` method for RPC API.
- [ ] Analyze received IO Schedule using regular expressions and define & document rules of passing following execution steps and phases
- [ ] New Engine Pallet is connected to Circuit node and installable as a new Pallet 
- [ ] Keep the context for the interoperable transaction
- [ ] Use off-chain workers client to dispatch the calls to external runtimes via gateways
- [ ] Analyze the response from gateways and temporarily assume it’s enough to validate the transaction’s security.

**Comment by MaciejBaj** [comment]
Closed by #47

**Comment by MaciejBaj** [comment]
Analyze received IO Schedule using regular expressions and define & document rules of passing following execution steps and phases was refactored by #50
