### ISSUE TITLE
Collator monitoring & alarming LAUNCHIN

### ISSUE THREAD

**Issue by chiefbiiko** [t3rn/t3rn#304]
### Item Type

Spike

### Description

We need to monitor our active collators. Might be done using the Prometheus integration readily available in a Substrate node. If not suitable we need an alternative approach providing essential node and collator metrics.

### Additional Information

Ultimately we want to arrive at a solution covering a.o.:

+ status visualizations, i.e. a browser or cli dashboard
  + per collator:
    + peer count
    + latest collation block
    + syncing y/n (maybe sync height)
    + pending extrinsics
    + free disk space
    + network connectivity
    + systemd service status
  + across collators
    + time since last block 
    + best block
    + finalized block

+ telegram alerting for fatal errors (disk full, no network, bad service status, no more collations)

more: https://github.com/paritytech/polkadot/tree/master/grafana

### Acceptance Criteria

Proposal for a monitoring and alarming approach:
+ documented
+ with implementation hints in aws cloudformation
+ solution can be set up for different collator sets (chains) easily

### Is the issue ready?

- [X] This issue is ready

**Comment by digitalsimboja** [comment]
@chiefbiiko Please assign task to me as I want to take it on.
Thanks
