### ISSUE TITLE
Prevent replay attack when confirming side effect

### ISSUE THREAD

**Issue by petscheit** [t3rn/t3rn#366]
## Expected behavior
We should have a check in place, that ensures a side_effect was executed on target after it was created on circuit. This could be achieved by recording the last know block height of target during side_effect creation, and ensuring the side_effect was executed in a block equal or higher. This greatly reduces the attack vector (which is quite small in the first place).

### Actual behavior
Currently, when a side_effect is submitted, we do not record the last known block number of target as part of the side_effect. As a result we have no way of ensuring, a side_effect was executed after it was created. It is a small attack vector, that would allow executors to resubmit a previously executed side_effect, if the side_effect is the same. (E.g. transfer of same amount to the same person in two different side_effects)

**Comment by AwesomeIbex** [comment]
P1
