### ISSUE TITLE
Executor: add rebalance by teleport functionality

### ISSUE THREAD

**Issue by petscheit** [t3rn/t3rn#472]
### Item Type

Task

### Description

To run indefinitely, the executor needs to be able to rebalance its funds. As its being paid on T0RN, but is sending funds to another chain, at some point some of that T0RN needs to be converted into the target assets that users are looking to send.

- [ ] successfully teleport T0RN token to basilisk on rococo
- [ ] swap received T0RN TO BSX and/or other assets
- [ ] add rebalance trigger logic to the executor. At a certain point, the executor needs to start the rebalancing, as to not run out of funds 

### Acceptance Criteria

- executor can set a rather static (if, then) rebalancing strategy
- can now run without running out of assets

### What are the points assigned to this item?

3

### Is the issue ready?

- [X] This issue is ready

**Comment by MaciejBaj** [comment]
Blocked by install pallet-xbi to Circuit github.com/t3rn/pallet-xbi/issues/25
