### ISSUE TITLE
Portal: Arbitrary Inclusion Proofs

### ISSUE THREAD

**Issue by petscheit** [t3rn/t3rn#537]
### Item Type

Epic

### Description

The end goal for the light clients connected to portal is to enable inclusion proofs of any kind to be verifiable. These proofs include arbitrary events, balance proofs, or proving the inclusion of a transaction in a specific block. All of this functionality must also be invokable via smart contract precompiles.

A big chunk of work for this functionality will be decoding/encoding the different parameters. This is a two-step problem:

1. Docoding with native encodings of the target:
Potentially, every chain has a different encoding scheme. Eth uses RLP, while substrate uses SCALE. We must be able to interpret the encoding and map them to native rust types. This allows us to interpret arbitrary external decodings.

2. Dealing with generic return types:
After decoding, e.g. an event, we have to be able to access the decoded parameters. For example, when a smart contract submits the inclusion proofs for a specific event, we need to return the parameters of an included event. To make this generic, we need to 
a) encoded the decoded parameters (from 1.) in FVs, using the same schema 
b) implement decoding logic, that can be run in smart contracts, allowing the parameters to be used

This should look something like this in the end:

1) SC receives encoded inclusion proof from Eth target:
```solidity
struct Transfer {
    from: address,
    to: address,
    amount: u256,
    asset: address
}

let tran: Transfer = Portal::Ethereum::verify_and_decode_event(proof, Transfer);

```

Under the hood the following happens:
- FV receives encoded proof and event struct
- proof is verifies it and decodes the parameters, mapping them to rust natives
- FV now encodes the parameters into a new encoding, making it decodable in other places. FV return of type `Vec<u8>`
- In the SC, the parameters are decoded automatically, under the hood doing something like `Transfer::decode(encoded_paras)`

Currently not all tickets are written yet, namely for running other inclusion proof types, like balance proofs, etc.

## Tickets
- [x] #532 
- [x] #533 

### Acceptance Criteria

.

### What are the points assigned to this item?

None

### Is the issue ready?

- [X] This issue is ready

**Comment by MaciejBaj** [comment]
Blocked by #647
