### ISSUE TITLE
Replace current ABI with SFX Messaging Protocol 

### ISSUE THREAD

**Issue by MaciejBaj** [t3rn/t3rn#564]
---
category: **Story**
title: Replace current ABI with SFX Messaging Protocol 
---
### Epic
Messaging Protocol

### Scope
- MOD protocol::confirm::(xbi + sfx + eth)
- DEL protocol::abi
- USE XBI::SCABI
- ADD messaging protocol for SFX as new submodule

#### Input / Output
- SFX struct, primarily SFX::signature <=> call data byte[]
- byte[] (RLP-encoded eth call data) <=> SFX struct
- byte[] (SCALE-encoded runtime call data) <=> SFX struct
- Gateway types (Gateway ABI)

### Goal
Given SFX struct and Gateway ABI, generate SCALE-encoded runtime call data and RLP-encoded eth call data, and vice versa.

### Acceptance Criteria
- SFX struct to call data byte[] conversion translates to valid SCALE-encoded runtime call data and RLP-encoded eth call data for all SFX types:
  - SFX::Call
  - SFX::TransferAsset
  - SFX::TransferNative
  - SFX::Swap
  - SFX::AddLiquidity
  - SFX::RemoveLiquidity
  - SFX::GetPrice

### Logs

# Related tickets

https://github.com/t3rn/t3rn/issues/647

**Comment by AwesomeIbex** [comment]
8

**Comment by AwesomeIbex** [comment]
Maciej still refactoring due to current issues with Interfaces & ABI->RLP. Will bring into next sprint
