### ISSUE TITLE
Circuit Mock data should be statically stored somewhere

### ISSUE THREAD

**Issue by AwesomeIbex** [t3rn/t3rn#645]
### Item Type

Task

### Description

We currently push some 100k lines of mock data to the repo [here](https://github.com/t3rn/t3rn/tree/development/pallets/circuit/src/mock-data)

### Additional Information

Really, git is not for this sort of thing, since it forces our editors to index it, isn't really functionality and is more akin to LFS. 

We should store the data somewhere, either through git LFS or something else, which can also automatically generate and update the data later on, since it takes a little while to generate.

@3h4x might have some ideas on this.
@petscheit owns most of this data so might have ideas on how to generate in the future.

### Acceptance Criteria

Mock data is removed from the repo and gathered elsewhere.

### What are the points assigned to this item?

2

### Is the issue ready?

- [ ] This issue is ready

**Comment by 3h4x** [comment]
external, versionable storage that is very cheap is S3 on AWS
we already have public bucket s3://public.t3rn.io where anyone could fetch stuff so Id put it there

it would require prerequirement in README or some script tho to fetch it before tests and updating GHA and whatever run tests

**Comment by petscheit** [comment]
Agreed, this is bad form. We need to figure out how to integrate this into our testing setup, ideally autogenerating new data from time to time to use in unit tests.

**Comment by AwesomeIbex** [comment]
I think an external process can keep this data consistent, the tests should just pull this from S3 or so.
