### ISSUE TITLE
chore: clarify parameters for contractsRegistry.addNewContract()

### ISSUE THREAD

**Issue by chiefbiiko** [t3rn/t3rn#696]
## Description

Adding a contract to the registry is somewhat cumbersome - there are many parameters to fill on the Polkadot.js Apps UI and it is not clear what values each of the inputs accept. Confusing params include:

+ `contract.actionDescriptions` : unclear
+ `meta.metadataVersion` : registry doesn't have any versioning yet, oder?
+ `meta.contractType` : unclear
+ `contract.author.feesPerSingleUse` : unclear what means single use? which method?
+ `contract.abi` : Shouldn't it be required for a registered contract?

### Acceptance Criteria

+ [ ] Extended Rust docs for [`RegistryContract`](https://github.com/t3rn/t3rn/blob/904a026ba0126ee2851c1c09d50c1f6e6f83206e/primitives/src/contracts_registry.rs#L57) and Co
+ [ ] Define a few `contractsRegistry.addNewContract()` test cases in zombienet

Given the test suite we can iterate a build-test cycle until the API is convenient.

### Additional Information

Furthermore we should start building a dedicated contracts (upload, dashboard, interact) page into our dapp to streamline dev onboarding onto t3rn.

**Comment by AwesomeIbex** [comment]
Duplicate of https://github.com/t3rn/3vm/issues/129
