### ISSUE TITLE
Testing: setup private Eth2 network

### ISSUE THREAD

**Issue by petscheit** [t3rn/t3rn#710]
### Item Type

Story

### Description

For testing, we need to setup a private Eth2 network, allowing us to run full lifecycle tests in a testing environment, while simulating hard forks, ensuring perpetual compatibility. 

Tasks:

- [ ] create custom network config, closely mirroring eth2 mainnet (with a lot fewer validators)
- [ ] create a container for Beaconchain and Execution chain client
- [ ] create a startup script, starting the network at genesis
- [ ] ensure we can configure the block height where hardforks go into effect
- [ ] ensure we can create balances for arbitrary accounts

In the end, the network should behave like mainnet, allowing us to make transactions, deploy contracts, etc.

### Acceptance Criteria

- the network can initialized via a single startup script, allowing clients to connect
- The network does not persist state between runs

### What are the points assigned to this item?

None

### Is the issue ready?

- [X] This issue is ready

**Comment by AwesomeIbex** [comment]
Add config here

**Comment by 3h4x** [comment]
Two approach were done in two different PRs:

1. https://github.com/t3rn/t3rn/pull/854 

[Copy of lighthouse test network](https://github.com/sigp/lighthouse/tree/unstable/scripts/local_testnet) 
Consist of ganache as execution layer and lighthouse as beacon node + validators. Everything run as bash script.

Ganache in [release v7.8.0](https://github.com/trufflesuite/ganache/releases/tag/v7.8.0),  which is current at the time of writing, should support Shanghai according to release notes.

Errors from logs when trying to do merge hardfork:
```
Apr 20 10:42:37.227 WARN Error during exchange capabilities      error: ServerMessage { code: -32700, message: "The method engine_exchangeCapabilities does not exist/is not available" }, service: exec
Apr 20 10:42:37.501 WARN Low peer count                          peer_count: 0, service: slot_notifier
Apr 20 10:42:37.501 INFO Synced                                  slot: 32, block:    …  empty, epoch: 1, finalized_epoch: 0, finalized_root: 0x0e08…cd7c, exec_hash: n/a, peers: 0, service: slot_notifier
Apr 20 10:42:37.502 WARN Syncing deposit contract block cache    est_blocks_remaining: 11, service: slot_notifier
Apr 20 10:42:37.502 WARN Execution engine call failed            error: ServerMessage { code: -32700, message: "**The method engine_exchangeTransitionConfigurationV1 does not exist**/is not available" }, service: exec
Apr 20 10:42:37.502 ERRO Unable to get transition config         error: Api { error: ServerMessage { code: -32700, message: "The method engine_exchangeTransitionConfigurationV1 does not exist/is not available" } }, service: exec
```

2. https://github.com/t3rn/chainops/pull/429

Based on https://github.com/petscheit/lighthouse-docker

This is single docker-compose which runs geth, lighthouse and validator.

**Comment by 3h4x** [comment]
reopen
