### ISSUE TITLE
Executor: Add state persistence

### ISSUE THREAD

**Issue by petscheit** [t3rn/t3rn#718]
### Item Type

Task

### Description

Currently, the executor is a stateful application but does not persist any of it. When crashing, the executor is not able to figure out which SFXs it was executing, resulting in slashing. For this reason, data persistence is required. On application restart, we want to automatically restore the previous state, ensuring we continue with the execution as if no crash occurred. 

### Acceptance Criteria

As an Executor, a restart of the application will result in no important execution data missing. Any SFX execution will continue as if nothing happened. 

### What are the points assigned to this item?

None

### Is the issue ready?

- [X] This issue is ready

**Comment by ahkohd** [comment]
Here's an improved version of your response:

In terms of state handling, there are several options available in JavaScript, including global objects, Redux, MobX, and observables.

If you're using a global object to manage state, you can use the [Reflect API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect) in JavaScript to detect when a property of the object is updated. When this happens, you can serialize the entire object to JSON and write it to disk. Alternatively, you can define a function that updates the state object and then serializes and writes it to disk. Here's an example:

```js
function updateState(state, field, value) {
  state[field] = value;
  const serializedState = JSON.stringify(state);
  // write to disk
}

// usage
updateState(myState, 'myField', 'Hello, World!');
```

If you're using Redux, there are several libraries available to persist and store the state to disk, including `redux-persist` and `redux-offline`.

If you're using observables, you can subscribe to the observable and write the emitted data to disk.

In terms of error handling, Node.js provides the `process.on('uncaughtException')` event to detect unhandled exceptions that might result in a crash. You can use this event to log the error or perform some other final actions before the Node.js process terminates. For example:

```js
process.on('uncaughtException', function(err) {
  console.log('Caught exception: ' + err);
  // (optional): we should be able to serialize the state here as well.
});
```

After restarting the application, you can rehydrate the state from the serialized JSON that you wrote to disk.

**Comment by AwesomeIbex** [comment]
@ahkohd get as much info from @chiefbiiko as possible
