### ISSUE TITLE
ci: contracts testing

### ISSUE THREAD

**Issue by chiefbiiko** [t3rn/t3rn#720]
### Item Type

Story

### Description

Incorporate contracts interactions into our CI test suites.

### Additional Information

The test suite shall serve as quality assurance measurement as well as a blueprint on contract interaction for a subsequent frontend integration.

### Acceptance Criteria

- [ ] GHA pipeline triggered when merging/pushing to development
- [ ] Test coverage
  - [ ] Adding contracts to the registry
    - [ ] EVM
    - [ ] WASM
  - [ ] Calling contracts
    - [ ] EVM
    - [ ] WASM
  - [ ] Contract execution rewards

### What are the points assigned to this item?

5

### Is the issue ready?

- [X] This issue is ready

**Comment by AwesomeIbex** [comment]
We already do this in 3vm tests
