### ISSUE TITLE
Portal: remove header submission extrinsic from portal

### ISSUE THREAD

**Issue by petscheit** [t3rn/t3rn#727]
### Item Type

Task

### Description

To simplify the type encodings, move the FV header submission away from portal and expose in the respective FV. This will make client-side type encodings much simple and saves us a couple of decoding steps. 

- [ ] reexpose extrinsic in FV pallet
- [ ] expose and rename FV types 
- [ ] update CLI and eventually ranger to support the changes

### Acceptance Criteria

As a ranger, I am now able to submit the headers directly to the FV pallet.

### What are the points assigned to this item?

None

### Is the issue ready?

- [X] This issue is ready

**Comment by AwesomeIbex** [comment]
1
