### ISSUE TITLE
CLI: Implement eth2

### ISSUE THREAD

**Issue by petscheit** [t3rn/t3rn#936]
## Description
As we will be rolling the Eth2 pallet out soonish, we need to implement the pallet-specific commands into the CLI. I will update this ticket soonish with some examples for sourcing the data.

To register, we must pass [this struct](https://github.com/t3rn/eth2-light-client/blob/main/src/types.rs#L67), an the encoded_registration_data to portal. The data can be generated via the initialize function [here](https://github.com/t3rn/eth2-light-client/blob/feat/eth2-pallet/client/packages/eth2-client/src/index.ts#LL20C17-L20C17). All required parameters are generated in the query module, no need to implement this rawHeader stuff that comes after `const initData = await fetchInitData(slot);`

### Tasks
- [x] Implement registration of eth2 into the CLI. Main thing here is gathering the eth2 specific data

### Acceptance Criteria

Please describe the conditions which must be met for this issue to close

**Comment by ahkohd** [comment]
The main task is done; I think we should close this ticket.
